-- =====================================================================
-- PostgreSQL 建表脚本（云端持久化使用）
-- 使用 CREATE TABLE IF NOT EXISTS 保证重复执行幂等（不覆盖已有数据）。
-- 由 application-pg.yml 的 spring.sql.init 在启动时自动执行。
-- =====================================================================

CREATE TABLE IF NOT EXISTS sys_user (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(20) NOT NULL,
  password VARCHAR(100) NOT NULL,
  role VARCHAR(16) NOT NULL,
  teacher_id BIGINT DEFAULT NULL,
  is_init_password SMALLINT NOT NULL DEFAULT 1,
  pwd_version INT NOT NULL DEFAULT 0,
  create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_username UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS weekly_report (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL,
  week_year VARCHAR(20) NOT NULL,
  content_work TEXT NOT NULL,
  content_problem TEXT NOT NULL,
  content_next TEXT NOT NULL,
  content_literature TEXT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'draft',
  teacher_comment TEXT DEFAULT NULL,
  create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  submit_at TIMESTAMP DEFAULT NULL,
  review_at TIMESTAMP DEFAULT NULL,
  CONSTRAINT uk_student_week UNIQUE (student_id, week_year)
);

CREATE INDEX IF NOT EXISTS idx_student_id ON weekly_report (student_id);
